[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/0honus0/SubconverterRule/master/Proxy"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Global.list"

# ç”µæŠ¥ä¿¡æ¯
[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/0honus0/SubconverterRule/master/Direct"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/NobyDa/Script/master/Surge/WeChat.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/0honus0/SubconverterRule/master/Reject"

[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

# [[rulesets]]
# group = "ğŸ¥ NETFLIX"
# ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Video/Netflix.list"

# [[rulesets]]
# group = "ğŸŒ å›½å†…åª’ä½“"
# ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"

# [[rulesets]]
# group = "ğŸŒ å›½å†…åª’ä½“"
# ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/iQiyi.list"

# [[rulesets]]
# group = "ğŸŒ å›½å†…åª’ä½“"
# ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Letv.list"

# [[rulesets]]
# group = "ğŸŒ å›½å†…åª’ä½“"
# ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/MOO.list"

# [[rulesets]]
# group = "ğŸŒ å›½å†…åª’ä½“"
# ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Tencent Video.list"

# [[rulesets]]
# group = "ğŸŒ å›½å†…åª’ä½“"
# ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Youku.list"